richardkiss/pycoin

pycoin/networks.py
As defined in Darkcoin Core:
https://github.com/darkcoin/darkcoin/blob/v0.11.0.x/src/chainparams.cpp#L69
https://github.com/darkcoin/darkcoin/blob/v0.11.0.x/src/chainparams.cpp#L136
/Edit, removed vertcoin, was broken.
=> Update Darkcoin prefixes.

pycoin/tx/Tx.py, pycoin/tx/script/vm.py
***WARNING: THIS NEEDS REVIEW!***
It probably also needs unit tests.
I'm not sure I follow all the logic that motivated the original change in c441ea75885167a809ae402d03e1066ed89d3804, so I'm probably not the best person to submit this patch. @richardkiss and @gitmarek, can you give your blessing on this? Better yet, can either of you submit a unit test that will appropriately fail with 412efbced6852b586bca8ba2f34f124c974b29c4 and/or c441ea75885167a809ae402d03e1066ed89d3804 with respect to #77?
=> Fix #77. Add second `script` parameter to remaining `signature_for_hash_type_f` in `verify_tx_in`.

pycoin/tx/TxOut.py
Alternate to #86 without additional changes.
=> Fix #85. Pass netcodes parameter through to subcall.

pycoin/tx/TxIn.py
Split the method TxIn.bitcoin_address() into two methods:
one attempts to return the public key of tx_in signature script,
the other, using the previous one, returns the corresponding
bitcoin address.
=> TxIn.public_key_sec(): Atempt to return the public key

pycoin/tx/pay_to/ScriptMultisig.py
when partially signing transactions and then sending it to other software to add more signatures some libraries don't deal well with the dummy signatures, so being able to disable the dummy signatures.
=> add kwarg to disable dummy signatures in ScriptMultisig

pycoin/services/insight.py, pycoin/tx/pay_to/ScriptUnknown.py
Minor/convenience fixes. Two scenarios:
1, Comprehensive exception instead of ugly HTTPError on InsightService.send_tx, such as:
<pre>ValueError: Transaction rejected by network (code -26). Reason: 64: non-canonical</pre>
2, Missing SolvingError import:
<pre>
>>> from pycoin.tx.pay_to import ScriptUnknown
>>> script = ScriptUnknown('abc')
>>> script.solve()
Traceback (most recent call last):
File "<input>", line 1, in <module>
File "build/bdist.linux-x86_64/egg/pycoin/tx/pay_to/ScriptUnknown.py", line 16, in solve
raise SolvingError("unknown script type")
NameError: global name 'SolvingError' is not defined
</pre>
Thanks Richard for the awesome work
=> InsightService.send_tx error handling, missing imports

pycoin/tx/pay_to/ScriptMultisig.py, tests/pay_to_test.py
Credits @devrandom
Adding a test case
The test will get current HEAD confused on a redeem script:
```
def remove_sequence(string):
if not string.startswith(b"\x30"):
raise UnexpectedDER(
"wanted sequence (0x30), got string length %d %s" % (
>                   len(string), binascii.hexlify(string[:10])))
E           UnexpectedDER: wanted sequence (0x30), got string length 104 52210234abcffd2e80ad
pycoin/tx/script/der.py:62: UnexpectedDER
```
=> don't parse too many sigs in P2SH + OP_CHECKMULTISIG sig ordering + tests

pycoin/ecdsa/ellipticcurve.py, pycoin/ecdsa/native/library.py, pycoin/ecdsa/numbertheory.py
Most cloud environment (such as Appengine) does not support C modules (ctypes) in Python environment (reference: [Appengine documentation](https://cloud.google.com/appengine/kb/libraries)).
This commit https://github.com/richardkiss/pycoin/commit/43952daee3ec6e7077e4cef435bf0bcd05cd2096 made pycoin unusable in such environments. This PR solves the compatibility issue
=> Compatibility with Appengine and some other environments

pycoin/ecdsa/__init__.py, pycoin/tx/pay_to/ScriptType.py, pycoin/tx/script/check_signature.py
When signing txs with op_checkmultisig in them, this would show up in the console:
`No handlers could be found for logger "pycoin.tx.script.vm"`
It confused me a lot when I was getting familiar with pycoin. Turns out it can't place a dummy signature on the curve:
```
ERROR:pycoin.tx.script.vm:script failed
Traceback (most recent call last):
File "build/bdist.linux-x86_64/egg/pycoin/tx/script/vm.py", line 126, in eval_script
stack, signature_for_hash_type_f, expected_hash_type, script[begin_code_hash:])
File "build/bdist.linux-x86_64/egg/pycoin/tx/script/check_signature.py", line 152, in op_checkmultisig
sig_blobs, public_pairs, tmp_script, signature_for_hash_type_f, strict_checks=True)
File "build/bdist.linux-x86_64/egg/pycoin/tx/script/check_signature.py", line 101, in sig_blob_matches …
```
=> READY: eval_script op_checkmultisig to not log an exception on dummy signatures

pycoin/tx/tx_utils.py
multisig signing ( and partially sign) support for Bitcoin testnet and other supported altcoins (all networks included in networks.py), default to BTC
- passing the appropriate allowable_wif_prefix defined in networks.py instead of the hardcoded bitcoin wif prefix
=> multisig support for testnet and altcoins

pycoin/intbytes.py, pycoin/tx/script/tools.py, tests/validate_tx_test.py
In 0.42 get_opcode in Python 2 correctly used little endian integers parsing (https://github.com/richardkiss/pycoin/blob/0.42/pycoin/tx/script/tools.py#L52), but in 0.60 it now uses big endian. This causes larger sizes to be parsed incorrectly.
For Python 3.2+, the bug was always there.
=> Fixed get_opcode for sizes larger than 1 byte

pycoin/tx/script/tools.py
`int_to_bytes` import was removed in 55c606a9e7bd05033cec782db95ce3a40f853c8c, but a reference to it was re-added in 5570049ff000509105790eaf5dc55ab1ea495e32. This change re-adds the import.
=> Fixed NameError for int_to_bytes

pycoin/networks.py
I've added DFC to the networks.py file to add support for the DEFCOIN cryptocurrency.
Although it's not valuable, DEFCOINs are used at the world's largest hacker conference - DEFCON - in Las Vegas every year. This simple patch adds support for it.
=> Added DEFCOIN (DFC) support to networks.py

pycoin/tx/Tx.py
sign_tx_in should pass the given hash_type instead of default to SIGHASH_ALL
=> sign_tx_in should pass hash_type

pycoin/services/blockr_io.py
Blockr.io's spendables_for_address method silently failed due to the use of non-existent self.base_url.
=> Fix blockrio's spendables_for_address method

pycoin/networks/legacy_networks.py
DASH addressversion for testnet has changed in 12.1 - only y addresses are correct
=> [networks.py] Dash testnet address start with y

pycoin/services/blockchain_info.py, pycoin/services/blockexplorer.py, pycoin/services/blockr_io.py
I found a few services that were using cleartext HTTP when they have HTTPS available.
=> Switch a few HTTP connections to HTTPS because encryption is great

pycoin/services/blockcypher.py
Because blockchain.info doesn't support OP_RETURN transactions.
=> Add broadcast_tx endpoint to blockcypher API.

pycoin/contrib/msg_signing.py, tests/msg_signing_test.py
=> Handle py3 case of bytes (not string) being provided as signature

BIP32.txt, README.md
Change urls to markdown links.
Formatted non-code as non-code, so descriptive writing was not formatted as code.
Change triple back ticks to single back ticks for inline code.
=> Update markdown in the README

pycoin/cmds/tx.py
Currently, tx command described in https://github.com/richardkiss/pycoin/blob/master/COMMAND-LINE-TOOLS.md shows error when try out this line.
I just fixed it.
```
$ tx -F 85000 -i 12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjrJX 1KissFDVu2wAYWPRm4UGh5ZCDU9sE9an8T 1KissEskteXTAXbh17qJYLtMes1B6kJxZj 12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjrJX/50
Traceback (most recent call last):
File "/Users/shunusami/.anyenv/envs/pyenv/versions/3.5.2/bin/tx", line 9, in <module>
load_entry_point('pycoin==0.77', 'console_scripts', 'tx')()
File "/Users/shunusami/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pycoin/cmds/tx.py", line 475, in main
warning_tx_cache, warning_tx_for_tx_hash, warning_spendables) = parse_context(args, parser)
File "/Users/shunusami/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pycoin/cmds/tx.py", …
```
=> fix tx.py line 517

pycoin/tx/Tx.py
BIP143 states that hashoutputs uses the same serialization as TxOutput, which is as a varint prefixed buffer for the script, not a push of the bytes. This matches e.g. core/c-lightning/rust-bitcoin/liquid/bitcoinj etc.
=> Don't write txout scripts as data pushes for segwit preimage creation

pycoin/cmds/ku.py
The "ku" tool currently lacks the ability to read keys from the standard input (which also makes piping impossible). Oftentimes a private key will be supplied from another tool, in which case the ability to pipe data in is necessary.
This commit makes it possible to take data in from stdin when no positional arguments are present.
=> Add the ability to read input data from stdin

pycoin/block.py, tests/parse_block_test.py
This PR allows faster parsing in case the blocks are retrieved from a trusted source (e.g. a local Bitcoin node).
=> Allow skipping Block.check_merkle_hash() for validated blocks

pycoin/message/make_parser_and_packer.py
=> BIP130 support: add sendheaders message in P2P messages

pycoin/symbols/xch.py
using XTN to get network, will get bitcoin network Tx as default, but it is not right to build BCH transaction because of the wrong SIGHASH_FORKID.
so add a new network XCH, it will be OK.
=> 2018-10-27 add BCash testnet(XCH) network

pycoin/ecdsa/Generator.py, tests/key_test.py
ECDSA has a subtle edge case. If the value to sign is 0, then anyone can forge a signature
by picking (r,s) = (public_key.x, public_key.x).
ref: https://crypto.stackexchange.com/questions/50279/how-should-ecdsa-handle-the-null-hash
Signing is --- working mod n --- supposed to be this:
(x,y) := k*G
r := x
s := inverse(k) * (val + (secret_exponent * r))
and verifying is
u1 := val * inverse(s)
u2 := r * inverse(s)
(x',y') := u1 * G + u2 * public_key
= (val*inverse(s)) * G + (r * inverse(s)) * public_key
But if val = 0 this collapses to
= (0*inverse(s)) * G + (r * inverse(s)) * public_key
= (r * inverse(s)) * public_key
And then as a forger I can lie and pick s := r so that this becomes
= (r * inverse(r)) * public_key
= public_key
So I know what value I need r to be to pass verification: r := …
=> Disallow the zero ECDSA message.

pycoin/ecdsa/rfc6979.py
Hi Richard, I hope you are well 🐰
I believe the implementation has a tiny mistake that occurs when the input happens
to equal the group order (eg `z = p256k1_N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141`).
https://tools.ietf.org/html/rfc6979#section-2.3.4 says:
>    2.  z1 is reduced modulo q, yielding z2 (an integer between 0 and
>       q-1, inclusive):
>
>          z2 = z1 mod q
>
>       Note that since z1 is less than 2^qlen, that modular reduction
>       can be implemented with a simple conditional subtraction:
>       z2 = z1-q if that value is non-negative; otherwise, z2 = z1.
Here val = z1, and n = q. It's saying:
```
z2 = z1 - q if (z1 - q >= 0) else z1
```
which is the same as
```
val = z1; n = q;
if val - n >= 0:
val = val - n
```
which is the same …
=> Round down deterministic-K input at the edge of the group size

pycoin/symbols/ltc.py, pycoin/symbols/xlt.py, tests/cmds/test_cases/ku/bip32_subpaths_ltc.txt, tests/cmds/test_cases/ku/bip32_subpaths_xlt.txt
Update the Litecoin HRP for main net and test net, as discussed in https://github.com/richardkiss/pycoin/issues/323
Once updated, litecoind is able to validate bech32 addresses:
```
input                         : create
network                       : Litecoin mainnet
netcode                       : LTC
wallet key                    : Ltpv71G8qDifUiNetk8cGMfWDtkSQA8zGwhGkQaZJT6a4h562SGjUKJkStcQKh5LeA\
uq8n3PsBkL8avNNscfCi4khqP6KePCBtiig63VxEGmueh
public version                : Ltub2SSUS19CirucWcqSWy9tJUaeqiqBMCFvpvgayRrrzsrgcoTooEMBTVifa3APbv\
o96vpuXG4gNkQFCzrbuiuTxuMURbZnpFNBL77u3pwibnX
tree depth                    : 0
fingerprint                   : e346dcb1
parent f'print                : 00000000
child index                   : 0
chain code                    : …
```
=> fix ltc hrp

pycoin/ecdsa/Generator.py
- According to sec1-v2 (http://www.secg.org/sec1-v2.pdf) Section 4.1.3, r should be modulo by curve.order;
- p1[1] would never greater than curve.p due to the modulo curve.p operation in Curve.add();
- https://github.com/richardkiss/pycoin/blob/master/pycoin/ecdsa/Curve.py#L67
- recovery id is added with 2 in the overflow condition when p1[0] > curve.order;
- https://github.com/indutny/elliptic/blob/776c9b0e99832ab9fa6c5fa6f684c484ca5265b2/lib/elliptic/ec/index.js#L141
- https://github.com/bitcoin-core/secp256k1/blob/1e6f1f5ad5e7f1e3ef79313ec02023902bf8175c/src/ecdsa_impl.h#L288
- There is only 1/2^127 chance to trigger this overflow condition (A.K.A, this bug);
=> correct generation of r and recid

pycoin/vm/ScriptTools.py
Upgrading from `0.80` to `0.90.20200322` the call below is now broken. This PR fixes the issue of having `signature_placeholder = None`.
```python
signature_placeholder = None
network.tx_utils.sign_tx(
tx, wifs=private_keys, p2sh_lookup=p2sh_lookup, hash_type=network.validator.flags.SIGHASH_ALL | SIGHASH_FORKID,
signature_placeholder=signature_placeholder
)
```
Stack trace
```
venv/lib/python3.6/site-packages/pycoin/networks/bitcoinish.py:275: in my_sign_tx
return sign_tx(network, *args, **kwargs)
venv/lib/python3.6/site-packages/pycoin/coins/tx_utils.py:131: in sign_tx
solver.sign(keychain, **kwargs)
venv/lib/python3.6/site-packages/pycoin/coins/bitcoin/Solver.py:170: in sign
r = self.solve(hash160_lookup, tx_in_idx, hash_type=hash_type, **kwargs) …
```
=> allow None as default_placeholder when signing tx

pycoin/ecdsa/native/openssl.py
There is a small typo in pycoin/ecdsa/native/openssl.py.
Should read `multiplication` rather than `mulitiplication`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, mulitiplication -> multiplication

pycoin/key/bip32.py
I noticed that matt bogosian left columbia a long time ago. I found on the Web a new email address. So I replaced the columbia address with the new email address.
=> changed the email address of matt bogossian to its latest email address
