pycoin/key/Key.py
pycoin/scripts/genwallet.py
tests/bip32_test.py
tests/key_validate_test.py

*UPDATE: Ready for review, merge.*
~~I added unit tests as well, but I'm not sure [this](https://github.com/mbogosian/pycoin/compare/key-is-private-83?expand=1#diff-dfb8f8f151cb7982f743bdd4d16d4a8fR5) is the right approach.~~ *UPDATE: Fixed in 404f943.*
Tagging #83.

READY FOR REVIEW - Fix #83. Key.is_private -> Key.is_private() where appropriate.

---

pycoin/scripts/genwallet.py

Seems like the bitcoin_address api has changed at some point?

Fix the -a option in genwallet

---

pycoin/key/Key.py
pycoin/scripts/genwallet.py

Apologies if this doesn't quite work, hacking away from github. It's all pretty self-explanatory though. Thanks!

Fix genwallet -i option

---

pycoin/services/insight.py

InsightService.send_tx() was failing due to missing imports

missing imports for InsightService: io, urlencode

---

pycoin/scripts/tx.py

This PR adds a new tx.py command-line option `-s` / `--verbose-signature` which extracts the ECDSA 'r' and 's' values from each signature found in the scriptSig(s).
When used with the `-a` option, it also displays the calculated signature_hash() value, 'z'.
There aren't any unit tests (yet)—if anyone's aware of an alternate utility that could be used to validate the new output, it would certainly make sense to add some tests.

Add r, s, and z signature details to tx utility

---

tests/pay_to_test.py

This improves test cases to cover some examples from #146.
Note, some unrelated tests failed on my machine when testing these tests.

Improve ScriptNulldata tests to ensure short strings work okay.

---

pycoin/tx/tx_utils.py

I noticed that `create_signed_tx` doesn't support testnet, this should fix that.

support other netcodes in create_signed_tx

---

pycoin/ecdsa/numbertheory.py

fixed small bug when p == 2 and a couple of typos in documentation; used bitwise left shift operator to improve performance

fixed small bug and two typos, improved performance

---

pycoin/key/msg_signing.py
tests/msg_signing_test.py

New message signing feature:
- sign text with your Bitcoin (or altcoin) private key.
- verify signatures on messages
- parse / encode a commonly-observed RFC2440-like wrapper for those messages.

New message signing feature (functional style, with py3 support)

---

pycoin/key/Key.py
tests/key_test.py

You can now sign and verify hashes using the Key.

Added sign and verify to Key

---

CREDITS
pycoin/tx/pay_to/ScriptMultisig.py

To throw exception on Multisig script and address generation where it
was coded with N of M instead M of N. 
discussion:  https://github.com/richardkiss/pycoin/commit/08b7c7d4d636f4e0689929e3d6806467fcc2ab8a#commitcomment-19897678

throw exception on N of M multisig

---

pycoin/networks/legacy_networks.py

Support for Decred (https://www.decred.org)

added support for Decred (DCR)

---

pycoin/ecdsa/native/library.py

https://github.com/richardkiss/pycoin/issues/176

linux and osx openssl support

---

pycoin/networks/legacy_networks.py

source https://github.com/AXErunners/axe

add AXE support

---

pycoin/symbols/uno.py
pycoin/symbols/xmy.py

Updated Myriadcoin, removed UNO (51% event 07/2017)

---

pycoin/symbols/polis.py

Hope everything is correct.
Will add testnet soon.

Integrate POLIS mainnet

---

README.md

Fix readme, network.keys.private() renamed to .wif

---

tests/tools_test.py

Test for https://github.com/richardkiss/pycoin/pull/364

PR test 364

---

pycoin/symbols/grs.py

seeds: https://github.com/Groestlcoin/groestlcoin/blob/master/src/groestlcoin.cpp#L365-L368
magic bytes: https://github.com/Groestlcoin/groestlcoin/blob/master/src/groestlcoin.cpp#L346-L349

Update dns seeds and magic bytes

---

pycoin/symbols/xlt.py

According to https://bitcoin.stackexchange.com/questions/62781/litecoin-constants-and-prefixes

Support Q addresses for Litecoin testnet

---

pycoin/symbols/grsrt.py
pycoin/symbols/tgrs.py

@richardkiss This adds groestlcoin testnet and groestlcoin regtest.

Add groestlcoin testnet and regtest

---

pycoin/cmds/tx.py
pycoin/contrib/who_signed.py

I fixed two minor typos in docstrings

fixed minor typos in comments

---

pycoin/networks/ContractAPI.py

I found a typo in a variable and fixed it. Note that this variable is not currently used in the code, so I did not fix a current buggy behavior, but a possible future buggy behavior.

fixed a typo in code

---

pycoin/coins/bitcoin/Tx.py

removed a duplicated and unused initialization

removed unused code
